echo "Hello World"
echo "This is just a sample file"
echo "I am trying to learn Git"
echo "I will try pull, push, merge, commit"
echo "Let's gooo...."
echo "I created a new branch now and adding changes in it that are not present in main branch"
